alias grep='grep -i --color=auto'
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gaa='git add -A'
alias gb='git checkout -b $1'
alias gc='git commit -m $1'
alias gco='git checkout $1'
alias gp='git push'
alias gpull='git pull'
alias gpo='git push -u origin $(git branch --show-current)'
# TODO: Account for github changing base branch from master to main
alias gpmaster='git pull origin master'
alias tf='terraform'
alias kk='kubectl --kubeconfig $(pwd)/kubeconfig.yaml'
alias ecrlogin='eval $(aws --region us-east-1 ecr get-login --registry-ids XXXXXXXXXX --no-include-email)'
