alias diff='colordiff  '
alias ga='git add'
alias gaa='git add -A'
alias gb='git checkout -b $1'
alias gc='git commit -m $1'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git push'
alias gpmain='git pull origin main'
alias gpmaster='git pull origin master'
alias gpo='git push -u origin $(git branch --show-current)'
alias grep='grep -i --color=auto'
alias gs='git status'
alias hh='hstr'
alias l='ls -l'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias tf='terraform'
alias kk='kubectl --kubeconfig $(pwd)/kubeconfig.yaml'
alias kr='kubectl --kubeconfig $(pwd)/kubeconfig-readonly.yaml'
alias ecrlogin='eval $(aws --region us-east-1 ecr get-login --registry-ids xxxxxxxxxxxx --no-include-email) && eval $(aws --region us-west-2 ecr get-login --registry-ids xxxxxxxxxxxx --no-include-email)'
